import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Searchbar from "components/SearchBar";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>VinoFi - Investing, Stocks, Crypto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-3xl font-bold p-6">VinoFi</h1>
        <Searchbar />
      </main>
    </div>
  );
};

export default Home;
